UNSTRUCTURED_API_KEY='fu3rUlhyNDl7NiESZs7TqyPPymQOpK'
UNSTRUCTURED_API_SERVER='https://aiclub-16izaxf0.api.unstructuredapp.io'

OPENAI_API_KEY="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"
REPLICATE_API_TOKEN="r8_b1f3Xz5gJJGyMvCVPrVhUaKzrgfb3sZ0Fxvaf"

TAVILY_API_KEY="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"